name: Build and push Docker image
on:
  push:
    branches-ignore:
      - refs/tags/*
env:
  DOCKER_IMAGE_ORG: ghcr.io/evrardjp
  DOCKER_IMAGE_REPO: openvpn
  DOCKER_IMAGE_TAG: latest
  DOCKER_IMAGE_SRC: github.com/evrardjp/openvpn-container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Environment Variables
        run: |
          echo "build_date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push front image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: "${{env.DOCKER_IMAGE_ORG}}/${{env.DOCKER_IMAGE_REPO}}:${{env.DOCKER_IMAGE_TAG}}"
          labels: |
            org.opencontainers.image.source=https://${{ env.DOCKER_IMAGE_SRC }}
            org.opencontainers.image.created=${{ env.build_date }}
            org.opencontainers.image.description=openvpn client container
